version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dekiru
      - POSTGRES_PASSWORD=dekiru_pass
      - POSTGRES_DB=dekiru
    ports:
      - "5432:5432"
    volumes:
      - /tmp/db_data:/var/lib/postgresql/data